---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: fqdnnetworkpolicies-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fqdnnetworkpolicies-serving-cert
spec:
  dnsNames:
  - fqdnnetworkpolicies-webhook.{{ .Release.Namespace }}.svc
  - fqdnnetworkpolicies-webhook.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: fqdnnetworkpolicies-selfsigned-issuer
  secretName: {{ .Release.Name }}-webhook-server-cert
