---
apiVersion: v1
kind: Service
metadata:
  name: fqdnnetworkpolicies-webhook
  labels:
    {{- include "fqdn-policy.labels" . | nindent 4 }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: controller-manager
    {{- include "fqdn-policy.selectorLabels" . | nindent 4 }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/fqdnnetworkpolicies-serving-cert
  name: fqdnnetworkpolicies-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: fqdnnetworkpolicies-webhook
      namespace: {{ .Release.Namespace }}
      path: /mutate-networking-gke-io-v1alpha3-fqdnnetworkpolicy
  failurePolicy: Fail
  name: mutate.fqdnnetworkpolicy.gke.io
  rules:
  - apiGroups:
    - networking.gke.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - fqdnnetworkpolicies
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/fqdnnetworkpolicies-serving-cert
  name: fqdnnetworkpolicies-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: fqdnnetworkpolicies-webhook
      namespace: {{ .Release.Namespace }}
      path: /validate-networking-gke-io-v1alpha3-fqdnnetworkpolicy
  failurePolicy: Fail
  name: validate.fqdnnetworkpolicy.gke.io
  rules:
  - apiGroups:
    - networking.gke.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - fqdnnetworkpolicies
  sideEffects: None
