containerSecurityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532
  seccompProfile:
    type: RuntimeDefault
  allowPrivilegeEscalation: false

image:
  repository: "ghcr.io/delta10/fqdnnetworkpolicies/controller"
  tag: "0.4"

manager:
  extraArgs:
  - --zap-log-level=error
  - --skip-aaaa

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

replicas: 1

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 20Mi

deploymentAnnotations: {}
