name: Release Charts

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: azure/setup-helm@v4
        name: "Setup Helm"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: helm
          config: helm/crconfig.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
